wandb_version: 1

tasks_per_iteration:
  desc: null
  value: 5
num_shots:
  desc: null
  value: 15
outer_epochs:
  desc: null
  value: 25
inner_epochs:
  desc: null
  value: 20
inner_lr:
  desc: null
  value: 0.01
meta_lr:
  desc: null
  value: 0.01
inner_wd:
  desc: null
  value: 0.003
meta_wd:
  desc: null
  value: 0.001
inter_epoch_decay:
  desc: null
  value: false
meta_decay:
  desc: null
  value: false
val_shots:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 1
loss_type:
  desc: null
  value: iou
scheduler:
  desc: null
  value: exp
val_size:
  desc: null
  value: 0.1
weighted_update_type:
  desc: null
  value: mean
scheduler_params:
  desc: null
  value:
    gamma: 0.8
invert_weights:
  desc: null
  value: true
norm_type:
  desc: null
  value: instance
chart_name:
  desc: null
  value: Amphibian-U-Net-IDW-Mean
alpha:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682493449.036368
    t:
      1:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.7.12
      5: 0.15.0
      8:
      - 5
